### ISSUE TITLE
get_metadata.py  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by RamPD78** [bpb27/twitter_scraping#17]
Hi all, i am very new here, my first experience
just trying this script all goes fine till creating "all_ids.json" file.
Now when I go to next step get_metadata.py this command return with error as following: 

 python3 Desktop/twitter_scraping-master/get_metadata.py
Traceback (most recent call last):
  File "Desktop/twitter_scraping-master/get_metadata.py", line 1, in <module>
    import tweepy
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tweepy/streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax

have no idea how to fix this error.
Please give me some clue what to do.
Thanks a lot

**Comment by RamPD78** [comment]
Ok Solved the issue by searching more here.. 
problem was Python3.7 compatibility issue
find this [https://github.com/nyanye/tweepy/blob/dc68896016e02a249a24f2204b571592cbc46de2/tweepy/streaming.py](url) and solved my problem.
